# Cache gems in between builds
cache:
  paths:
    - vendor/bundle

build:
  stage: build
  image: ruby:2.7
  script:
    - bundle config set deployment 'true'
    - bundle install -j $(nproc) 
  only:
    - master

deploy:
  image: google/cloud-sdk:alpine
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - echo $SERVICE_ACCOUNT_KEY > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud app deploy --project=***REMOVED***
  after_script:
    - rm /tmp/$CI_PIPELINE_ID.json
