require:
  - rubocop-rails

# Allow long code blocks in system tests, since we don't want to be constantly logging in and out
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"
    - "production/**/*"
Metrics/AbcSize:
  Exclude:
    - "test/**/*"
ClassVars:
  Exclude:
    - "test/**/*"

# Rubocop complains about "task :download_prod => :environment do", but its necessary for rails
Style/HashSyntax:
  Exclude:
    - "lib/tasks/**/*"
