require:
  - rubocop-rails

inherit_gem:
  prettier: rubocop.yml

# Allow long code blocks...
Metrics/BlockLength:
  Exclude:
    - "test/system/**/*" # in system tests, since we don't want to be constantly logging in and out
    - "test/factories.rb" # in the factories spec, since it's recommended practice to have them all in one file

# Rubocop complains about "task :download_prod => :environment do", but its necessary for rails
Style/HashSyntax:
  Exclude:
    - "lib/tasks/**/*"
