require:
  - rubocop-rails

inherit_gem:
  prettier: rubocop.yml

# Allow long blocks in the system tests, because we don't want to be constantly logging in and out
Metrics/BlockLength:
  Exclude:
    - "test/system/**/*"
