entrypoint: bundle exec rails server -p $PORT
runtime: ruby27

env_variables:
  RAILS_DATABASE_HOST: "null"
  RAILS_DATABASE_SOCKET: "/cloudsql/***REMOVED***:australia-southeast1:rails-jqc-instance-v8"
  RAILS_ENV: production

instance_class: B2
basic_scaling:
  max_instances: 5
  idle_timeout: 10m

beta_settings:
  cloud_sql_instances: ***REMOVED***:australia-southeast1:rails-jqc-instance-v8
