entrypoint: bundle exec rails server Puma -p $PORT
runtime: ruby27

env_variables:
    SECRET_KEY_BASE: ***REMOVED***

instance_class: B2
basic_scaling:
  max_instances: 5
  idle_timeout: 10m

beta_settings:
    cloud_sql_instances: ***REMOVED***:australia-southeast1:rails-jqc-instance-v8
