entrypoint: bundle exec rails server Puma -p $PORT
runtime: ruby27

env_variables:
    SECRET_KEY_BASE: ***REMOVED***

beta_settings:
    cloud_sql_instances: ***REMOVED***:australia-southeast1:rails-jqc-instance
