# See here for list of installed packages under 'ubuntu-latest'
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

name: 'JQC Continuous Integration'
on:
  push:
    branches: ['develop']
jobs:
  run_tests:
    runs-on: 'ubuntu-latest'
    environment: 'test'
    env:
      RAILS_ENV: 'test'
      RAILS_MASTER_KEY: ${{ secrets.RAILS_CREDENTIALS_TEST_KEY }}
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'

      - name: 'Start Google Cloud SQL proxy'
        uses: 'tom-barone/gce-cloudsql-proxy-action@master'
        with:
          creds: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          instance: ${{ secrets.GOOGLE_CLOUD_SQL_INSTANCE }}
          port: 3306
          
      - name: 'Install Ruby and gems'
        uses: 'ruby/setup-ruby@v1'
        with:
          bundler-cache: true

      - name: 'Prepare the test database'
        run: 'bin/rails db:test:prepare'

      - name: 'Compile SCSS and JS assets'
        run: 'bin/rails assets:precompile'

      - name: 'Run tests'
        run: 'bin/rails test:all'
        
  deploy_staging:
    needs: ['run_tests']
    runs-on: 'ubuntu-latest'
    environment: 'deploy'
    env:
      RAILS_ENV: 'staging'
      # Allow us to migrate the staging & production databases
      RAILS_DATABASE_SOCKET: 'null'
      RAILS_DATABASE_HOST: '127.0.0.1'
      RAILS_DATABASE_PORT: 3306
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Start Google Cloud SQL proxy'
        uses: 'tom-barone/gce-cloudsql-proxy-action@master'
        with:
          creds: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          instance: ${{ secrets.GOOGLE_CLOUD_SQL_INSTANCE }}
          port: 3306

      - name: 'Install Ruby and gems'
        uses: 'ruby/setup-ruby@v1'
        with:
          bundler-cache: true

      - name: 'Add staging key to config dir'
        run: 'echo "${{ secrets.RAILS_CREDENTIALS_STAGING_KEY }}" > config/credentials/staging.key'

      - name: 'Copy the production database to the staging database'
        run: 'bin/rails db:copy_prod TARGET=STAGING'

      - name: 'Migrate the staging database'
        run: 'bin/rails db:migrate'

      - name: 'Compile SCSS and JS assets'
        run: 'bin/rails assets:precompile'

      - name: 'Deploy staging site'
        run: 'gcloud app deploy GAE_staging.yaml --project=${{ secrets.GOOGLE_APP_ENGINE_PROJECT }} --version=staging --no-promote --no-cache --quiet'

  test_staging:
    needs: ['deploy_staging']
    runs-on: 'ubuntu-latest'
    environment: 'deploy'
    env:
      RAILS_ENV: 'staging'
      RAILS_MASTER_KEY: ${{ secrets.RAILS_CREDENTIALS_STAGING_KEY }}
      TEST_HOST: ${{ secrets.STAGING_URL }}
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'

      - name: 'Install Ruby and gems'
        uses: 'ruby/setup-ruby@v1'
        with:
          bundler-cache: true

      - name: 'Run tests against the staging site'
        run: 'ruby production/sign_in_and_check_table_test.rb'
